name: PumpRoom Publish
description: GitHub Action to upload tasks to PumpRoom LMS
author: Inzhenerka.Tech

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: upload-cloud
  color: purple

# Define your inputs here.
inputs:
  root_dir:
    description: 'Directory to be archived and uploaded'
    required: false
    default: ''
  ignore:
    description: 'Files and directories to ignore (comma-separated)'
    required: false
    default: ''
  realm:
    description: 'Realm identifier for the repository'
    required: true
  repo_name:
    description: 'Repository name'
    required: true
  api_key:
    description: 'API key for authentication'
    required: true

runs:
  using: node20
  main: dist/index.js
